# Generated by Django 4.0.1 on 2022-01-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='GuestResponse',
        ),
    ]
