# Generated by Django 4.0.1 on 2022-01-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='binary',
            field=models.BooleanField(default=True, max_length=10),
        ),
    ]
