# Generated by Django 4.0.1 on 2022-01-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_answer_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='type',
        ),
        migrations.AddField(
            model_name='quiz',
            name='binary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='numOfQuestions',
            field=models.IntegerField(default=10),
        ),
    ]
