# Generated by Django 4.0.1 on 2022-01-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='binary',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
